apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-lwid
spec:
  acme:
    email: lucien.loiseau@ovhcloud.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-lwid-account-key
    solvers:
      - dns01:
          cnameStrategy: None
          webhook:
            groupName: acme.runtime.ovh
            solverName: ovh
            config:
              endpoint: ovh-eu
              authenticationMethod: application
              applicationKeyRef:
                name: ovh-credentials-lwid
                key: applicationKey
              applicationSecretRef:
                name: ovh-credentials-lwid
                key: applicationSecret
              applicationConsumerKeyRef:
                name: ovh-credentials-lwid
                key: consumerKey
